apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-py
  name: app-py
  namespace: default
spec:
  replicas: 20
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: app-py
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-py
    spec:
      containers:
      - image: docker.io/ansustiwaz/app-py:v2
        name: app-py
