apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-py
  labels:
    app: app-py
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app-py
  template:
    metadata:
      labels:
        app: app-py
    spec:
      containers:
      - name: app-py
        image: docker.io/ansustiwaz/app-py:latest
